apiVersion: v1
kind: Service
metadata:
  name: webcam-rtsp-service
  annotations:
    description: "RTSP server for USB webcam"
spec:
  selector:
    app: webcam-rtsp-server
  ports:
  - name: rtsp
    port: 8554
    targetPort: 8554
    protocol: TCP
  - name: udp-stream
    port: 5000
    targetPort: 5000
    protocol: UDP
  type: LoadBalancer