apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: esphome-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.178.0/24,10.8.0.0/24,10.42.0.0/24"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-office"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - esphome.mydomain.tld
      secretName: esphome-tls
  rules:
  - host: "esphome.mydomain.tld"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: esphome-web
            port:
              number: 6052