apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: motion
  name: motion
  namespace: domotica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motion
  strategy: {}
  template:
    metadata:
      labels:
        app: motion
    spec:
      containers:
      - image: travnewmatic/motion
        imagePullPolicy: Always
        resources:
          limits:
            memory: 6Gi
            cpu: "3.5"
          requests:
            memory: 1Gi
            cpu: "0.2"
        name: motion
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/video0
          name: webcam-0
        - mountPath: /dev/video1
          name: webcam-1
        ports:
        - containerPort: 8080
          name: control
          protocol: TCP
        - containerPort: 8081
          name: stream
          protocol: TCP
      volumes:
      - name: webcam-0
        hostPath:
          path: /dev/video0
      - name: webcam-1
        hostPath:
          path: /dev/video1