apiVersion: v1
kind: Service
metadata:
  name: motion-control
  namespace: domotica
spec:
  selector:
    app: motion
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: motion-stream
  namespace: domotica
spec:
  selector:
    app: motion
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081