apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
# NodePort per connessioni dirette
apiVersion: v1
kind: Service
metadata:  
  name: mysql-ext
  namespace: mysql
spec:
  selector:    
    app: mysql
  type: LoadBalancer
  ports:  
  - port: 3306
    targetPort: 3306
    protocol: TCP